### ISSUE TITLE
Documentation for installation process

### ISSUE THREAD

**Issue by telegrambotdev** [eidoriantan/messenger-translator#70]
can you write a better read me for installation ?

**Comment by eidoriantan** [comment]
Hi, I don't know what you mean by that but I'll try to clearly explain, add a screenshot and describe what does the bot do. If you have anything in mind, just file a pull request.

**Comment by eidoriantan** [comment]
I'm sorry, I'd just realized that your question is about the installation. Just give me a moment to write the instructions for the installation.

**Comment by telegrambotdev** [comment]
also your bot is awsome,if you can create a telegram translation bot too.

Thanks in adavance

**Comment by eidoriantan** [comment]
I never used telegram before, but that sounds interesting. I'll notify you if I planned or built one.

Anyway, I'd already pushed the `README.md` guide for installation. See 9b7047a
